# Name of your application. Used to uniquely configure containers.
service: ocapi

# Name of the container image.
image: lastradev/ocapi

# Deploy to these servers.
servers:
  web:
    hosts:
      - 150.136.105.238
    labels:
      traefik.http.routers.kiqr_cloud.rule: Host(`crimes.lastradev.com`)
      traefik.http.routers.kiqr_cloud_secure.entrypoints: websecure
      traefik.http.routers.kiqr_cloud_secure.rule: Host(`crimes.lastradev.com`)
      traefik.http.routers.kiqr_cloud_secure.tls: true
      traefik.http.routers.kiqr_cloud_secure.tls.certresolver: letsencrypt
    options:
      network: "private"

# Credentials for your image host.
registry:
  username: lastradev
  password:
    - DOCKER_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_PASSWORD
    - GDRIVE_API_KEY
  clear:
    MYSQL_USER: "ocapi"
    MYSQL_DATABASE: "ocapi_production"
    MYSQL_HOST: "ocapi-db"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "ocapi_storage:/rails/storage"


# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Use a different ssh user than root
ssh:
  user: ubuntu

# Configure builder setup (defaults to multi-arch images).
builder:
  # Build same-arch image locally (use for x86->x86)
  multiarch: false
#
#   # Build diff-arch image via remote server
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1
#
#   args:
#     RUBY_VERSION: 3.3.1
#   secrets:
#     - GITHUB_TOKEN
#     - RAILS_MASTER_KEY

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: mysql:8.0
    host: 150.136.105.238
    env:
      clear:
        MYSQL_USER: "ocapi"
        MYSQL_DATABASE: "ocapi_production"
        MYSQL_RANDOM_ROOT_PASSWORD: "true"
      secret:
        - MYSQL_PASSWORD
    directories:
      - data:/var/lib/mysql
    options:
      network: "private"

traefik:
  options:
    network: "private"
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "oscar.glastra@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web 
